services:
  redis:
    container_name: redis
    image: 'redis/redis-stack-server:latest'
    restart: on-failure:5
    volumes:
      - redis_data:/data

  twitch-chat:
    container_name: twitch-chat
    image: 'ghcr.io/dotabod/twitch-chat:master'
    restart: on-failure:5
    build:
      context: .
      dockerfile: ./packages/Dockerfile
      args:
        - DOTABOD_ENV=${DOTABOD_ENV:-development}
        - BUILD_CONTEXT=packages/twitch-chat
    hostname: twitch-chat
    environment:
      - DATABASE_URL
      - DB_SECRET
      - DB_URL
      - MONGO_URL
      - DOTABOD_ENV
      - TWITCH_BOT_PROVIDERID
      - TWITCH_CLIENT_ID
      - TWITCH_CLIENT_SECRET

  steam:
    container_name: steam
    image: 'ghcr.io/dotabod/steam:master'
    restart: on-failure:5
    build:
      context: .
      dockerfile: ./packages/Dockerfile
      args:
        - DOTABOD_ENV=${DOTABOD_ENV:-development}
        - BUILD_CONTEXT=packages/steam
    hostname: steam
    environment:
      - MONGO_URL
      - STEAM_PASS
      - STEAM_USER
      - STEAM_WEB_API
      - DOTABOD_ENV

  twitch-events:
    ports:
      - '5011:5011'
    container_name: twitch-events
    image: 'ghcr.io/dotabod/twitch-events:master'
    restart: on-failure:5
    build:
      context: .
      dockerfile: ./packages/Dockerfile
      args:
        - DOTABOD_ENV=${DOTABOD_ENV:-development}
        - BUILD_CONTEXT=packages/twitch-events
    hostname: twitch-events
    environment:
      - DATABASE_URL
      - DB_SECRET
      - DB_URL
      - EVENTSUB_HOST
      - MONGO_URL
      - DOTABOD_ENV
      - TWITCH_CLIENT_ID
      - TWITCH_BOT_PROVIDERID
      - TWITCH_CLIENT_SECRET
      - TWITCH_EVENTSUB_SECRET
      - HOST_TWITCH_CHAT

  dota:
    ports:
      - '5120:5120'
    container_name: dota
    image: 'ghcr.io/dotabod/dota:master'
    restart: on-failure:5
    depends_on:
      - redis
      - steam
      - twitch-chat
      - twitch-events
    # random
    build:
      context: .
      dockerfile: ./packages/Dockerfile
      args:
        - DOTABOD_ENV=${DOTABOD_ENV:-development}
        - BUILD_CONTEXT=packages/dota
    hostname: dota
    environment:
      - D2PT_TOKEN
      - COMMIT_HASH
      - DATABASE_URL
      - DB_SECRET
      - DB_URL
      - MONGO_URL
      - DOTABOD_ENV
      - STEAM_WEB_API
      - STRATZ_TOKEN
      - TWITCH_BOT_PROVIDERID
      - TWITCH_CLIENT_ID
      - TWITCH_CLIENT_SECRET
      - HOST_REDIS
      - HOST_STEAM
      - HOST_TWITCH_CHAT
      - HOST_TWITCH_EVENTS
      - TWITCH_EXT_CLIENT_ID
      - TWITCH_EXT_SECRET
    volumes:
      - steam_auth:/app/packages/dota/src/steam/volumes

volumes:
  steam_auth:
  redis_data:
networks:
  default:
    name: dotabod
