import { defineConfig } from 'oxfmt'
import ultracite from 'ultracite/oxfmt'

const agentIgnorePatterns = ['.agents/**']

export default defineConfig({
  ...ultracite,
  // Crowdin writes locale JSON with no trailing newline; oxfmt adds one back.
  // Formatting them created a push loop between the crowdin-download and
  // autofix workflows (new PR every 6h, forever). These files are generated —
  // don't format them.
  ignorePatterns: [
    ...(ultracite.ignorePatterns ?? []),
    '**/locales/**/*.json',
    // Generated by `supabase gen types`; format changes are overwritten.
    '**/db/supabase-types.ts',
    ...agentIgnorePatterns,
  ],
  printWidth: 100,
  semi: false,
  singleQuote: true,
  useTabs: false,
})
