import { defineConfig } from 'oxlint'
import antiSlop from 'ultracite/oxlint/anti-slop'
import core from 'ultracite/oxlint/core'
import { selectJsPlugins } from 'ultracite/oxlint/js-plugins'
import vitest from 'ultracite/oxlint/vitest'

// React Doctor is deliberately omitted: this is a Node.js service workspace.
// eslint-plugin-github currently loads typescript-eslint, which rejects the
// TypeScript 7 API. Keep the compatible quality rules while TS7 support lands.
const backendJsPlugins = selectJsPlugins(['sonarjs'])
const agentIgnorePatterns = ['.agents/**']

export default defineConfig({
  categories: {
    correctness: 'error',
  },
  env: {
    browser: false,
    builtin: true,
    node: true,
  },
  extends: [core, antiSlop, backendJsPlugins, vitest],
  ignorePatterns: [...(core.ignorePatterns ?? []), ...agentIgnorePatterns],
  // Re-declare selected packages so Knip sees the dynamic JS-plugin imports.
  jsPlugins: backendJsPlugins.jsPlugins,
  options: {
    reportUnusedDisableDirectives: 'error',
    typeAware: true,
    typeCheck: true,
  },
  overrides: [
    {
      // Generated by `supabase gen types`; its helper-type boilerplate unions
      // `never` (empty CompositeTypes/Enums) which trips this rule.
      files: ['**/db/supabase-types.ts'],
      rules: {
        'typescript/no-redundant-type-constituents': 'off',
      },
    },
  ],
  rules: {
    'no-unused-vars': [
      'error',
      {
        caughtErrorsIgnorePattern: '^_',
        destructuredArrayIgnorePattern: '^_',
        varsIgnorePattern: '^_',
      },
    ],
  },
})
