version: '3'

services:
  clip-processor-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./temp:/app/temp
      - ./assets:/app/assets
    environment:
      - PORT=5000
      - POCKETBASE_URL=http://pocketbase:8090
    restart: unless-stopped
    depends_on:
      - pocketbase

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    ports:
      - "8090:8090"
    volumes:
      - pocketbase-data:/pb_data
    restart: unless-stopped

volumes:
  pocketbase-data:
