version: '3'

services:
  clip-processor-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"  # Bind to localhost only
    volumes:
      - ./temp:/app/temp
      - ./assets:/app/assets
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres@db:5439/clip_processor
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app:/app/src
      - MAX_CONCURRENT_WORKERS=1  # Limit to one concurrent process
      - QUEUE_POLLING_INTERVAL=1  # Check queue every 1 second
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - "127.0.0.1:5439:5439"  # Bind to localhost only
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clip_processor
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M

volumes:
  postgres-data:
