services:
  clip-processor-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./temp:/app/temp
      - ./assets:/app/assets
    environment:
      - PORT=5000
    restart: unless-stopped
