version: '3'

services:
  clip-processor-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./temp:/app/temp
      - ./assets:/app/assets
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/clip_processor
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clip_processor
    restart: unless-stopped

volumes:
  postgres-data:
