version: '3'

services:
  clip-processor-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"  # Bind to localhost only
    volumes:
      - ./temp:/app/temp
      - ./assets:/app/assets
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/clip_processor
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app:/app/src
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - "127.0.0.1:5432:5432"  # Bind to localhost only
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clip_processor
    restart: unless-stopped

volumes:
  postgres-data:
