# Dockerfile.mongo
FROM mongo:4.4.6

# Copy your custom init.js file to the appropriate location
COPY ./services/mongodb/src/init.js /docker-entrypoint-initdb.d/init.js

# Set the execution permissions for the init.js file
RUN chmod +x /docker-entrypoint-initdb.d/init.js
