import HEROES_DATA from 'dotaconstants/build/heroes.json' with { type: 'json' }

const heroAliases: Record<string, string[]> = {
  npc_dota_hero_antimage: ['am'],
  npc_dota_hero_bloodseeker: ['bs'],
  npc_dota_hero_crystal_maiden: ['cm', 'rylai'],
  npc_dota_hero_drow_ranger: ['drow'],
  npc_dota_hero_earthshaker: ['es', 'shaker'],
  npc_dota_hero_juggernaut: ['jug'],
  npc_dota_hero_mirana: ['potm'],
  npc_dota_hero_morphling: ['morph'],
  npc_dota_hero_nevermore: ['sf'],
  npc_dota_hero_phantom_lancer: ['pl'],
  npc_dota_hero_sand_king: ['sk'],
  npc_dota_hero_storm_spirit: ['storm'],
  npc_dota_hero_vengefulspirit: ['venge', 'vs'],
  npc_dota_hero_windrunner: ['wr'],
  npc_dota_hero_shadow_shaman: ['ss', 'shaman', 'rhasta'],
  npc_dota_hero_tidehunter: ['tide'],
  npc_dota_hero_witch_doctor: ['wd', 'doc'],
  npc_dota_hero_riki: [],
  npc_dota_hero_enigma: ['nigma'],
  npc_dota_hero_tinker: ['tink'],
  npc_dota_hero_necrolyte: ['necro', 'necrolyte'],
  npc_dota_hero_warlock: ['wl'],
  npc_dota_hero_beastmaster: ['bm', 'beast'],
  npc_dota_hero_queenofpain: ['qop'],
  npc_dota_hero_venomancer: ['veno'],
  npc_dota_hero_faceless_void: ['fv', 'faceless', 'void'],
  npc_dota_hero_skeleton_king: ['wk'],
  npc_dota_hero_death_prophet: ['dp'],
  npc_dota_hero_phantom_assassin: ['pa'],
  npc_dota_hero_templar_assassin: ['ta', 'templar', 'lanaya'],
  npc_dota_hero_dragon_knight: ['dk'],
  npc_dota_hero_rattletrap: ['cw', 'clock'],
  npc_dota_hero_leshrac: ['lesh'],
  npc_dota_hero_furion: ['np', 'natures', 'prophet', 'furion'],
  npc_dota_hero_life_stealer: ['ls', 'naix'],
  npc_dota_hero_dark_seer: ['ds'],
  npc_dota_hero_omniknight: ['omni'],
  npc_dota_hero_enchantress: ['ench'],
  npc_dota_hero_huskar: ['husk'],
  npc_dota_hero_night_stalker: ['ns'],
  npc_dota_hero_broodmother: ['brood', 'bm'],
  npc_dota_hero_bounty_hunter: ['bh', 'bounty'],
  npc_dota_hero_jakiro: ['jak'],
  npc_dota_hero_batrider: ['bat'],
  npc_dota_hero_spectre: ['spec'],
  npc_dota_hero_ancient_apparition: ['aa'],
  npc_dota_hero_spirit_breaker: ['sb', 'bara'],
  npc_dota_hero_gyrocopter: ['gyro'],
  npc_dota_hero_alchemist: ['alch'],
  npc_dota_hero_invoker: ['invo', 'voker'],
  npc_dota_hero_silencer: ['nortrom'],
  npc_dota_hero_obsidian_destroyer: ['od'],
  npc_dota_hero_brewmaster: ['brew', 'panda'],
  npc_dota_hero_shadow_demon: ['sd'],
  npc_dota_hero_lone_druid: ['ld', 'lone'],
  npc_dota_hero_chaos_knight: ['ck', 'chaos'],
  npc_dota_hero_treant: ['treant', 'tree'],
  npc_dota_hero_ogre_magi: ['ogre'],
  npc_dota_hero_undying: ['undy', 'und'],
  npc_dota_hero_rubick: ['rub', 'rubi', 'rubik'],
  npc_dota_hero_disruptor: ['dis', 'thrall'],
  npc_dota_hero_nyx_assassin: ['nyx'],
  npc_dota_hero_naga_siren: ['naga', 'siren'],
  npc_dota_hero_keeper_of_the_light: ['kotl', 'keeper', 'ezalor'],
  npc_dota_hero_wisp: ['wisp'],
  npc_dota_hero_medusa: ['dusa', 'dussy'],
  npc_dota_hero_troll_warlord: ['troll'],
  npc_dota_hero_centaur: ['cent', 'centaur'],
  npc_dota_hero_magnataur: ['mag'],
  npc_dota_hero_shredder: ['timber'],
  npc_dota_hero_bristleback: ['bb', 'bristle'],
  npc_dota_hero_tusk: ['tuskarr'],
  npc_dota_hero_skywrath_mage: ['sky', 'skywrath'],
  npc_dota_hero_abaddon: ['aba', 'abba'],
  npc_dota_hero_elder_titan: ['et', 'elder'],
  npc_dota_hero_legion_commander: ['lc', 'legion'],
  npc_dota_hero_techies: ['tech'],
  npc_dota_hero_ember_spirit: ['ember'],
  npc_dota_hero_earth_spirit: ['earth', 'es'],
  npc_dota_hero_abyssal_underlord: ['ul', 'under', 'pitlord'],
  npc_dota_hero_terrorblade: ['tb', 'terror'],
  npc_dota_hero_winter_wyvern: ['ww', 'winter', 'wyvern'],
  npc_dota_hero_arc_warden: ['arc'],
  npc_dota_hero_monkey_king: ['mk', 'monkey'],
  npc_dota_hero_dark_willow: ['dw', 'willow'],
  npc_dota_hero_pangolier: ['pango'],
  npc_dota_hero_grimstroke: ['grim'],
  npc_dota_hero_hoodwink: ['hw', 'hoodwinkle'],
  npc_dota_hero_void_spirit: ['vs'],
  npc_dota_hero_snapfire: ['snap', 'mortimer', 'grandma', 'granny'],
  npc_dota_hero_dawnbreaker: ['db', 'dawn'],
  npc_dota_hero_marci: ['AYAYA'],
  npc_dota_hero_primal_beast: ['pb', 'primal'],
}

type HeroEntry = {
  id: number
  localized_name: string
  alias: string[]
}

export const heroes: Record<string, HeroEntry> = {}

for (const heroData of Object.values(HEROES_DATA)) {
  const name = heroData.name
  heroes[name] = {
    id: heroData.id,
    localized_name: heroData.localized_name,
    alias: heroAliases[name] ?? [],
  }
}
