name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: biomejs/setup-biome@v2
        with:
          version: latest
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --no-progress --frozen-lockfile
      - name: Run Biome
        run: biome ci .
      - name: Run TypeScript type check
        run: bun run typecheck
      - name: Run tests
        run: bun run test
