name: Crowdin Upload Source

on:
  push:
    branches:
      - master

jobs:
  upload:
    name: Upload new english text
    environment: "prod"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3.0.2
        id: changes
        with:
          filters: |
            crowdin:
              - packages/dota/locales/en/translation.json
              - packages/twitch/**/locales/en/translation.json

      - name: crowdin action
        if: steps.changes.outputs.crowdin == 'true'
        uses: crowdin/github-action@v1.6.0
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
