name: Lint PR
on:
  pull_request:
    types: [assigned, opened, edited, synchronize, reopened]

jobs:
  commit:
    if: (github.actor != 'dependabot[bot]') && (contains(github.head_ref, 'dependabot/') == false)
    name: Lint Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5

  branch:
    if: (github.actor != 'dependabot[bot]') && (contains(github.head_ref, 'dependabot/') == false)
    name: Lint Branch
    runs-on: ubuntu-latest
    steps:
      - uses: lekterable/branchlint-action@1.2.0
        with:
          error: 'Branch name must start with `fix/`, `feat/`, or `release/` - `skip-release/` will skip the release workflow.'
          allowed: |
            /((release|feat|fix|skip-release)\/[a-zA-Z0-9]*[a-zA-Z0-9])|(stage)/

  title:
    if: (github.actor != 'dependabot[bot]') && (contains(github.head_ref, 'dependabot/') == false)
    name: Lint Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


