# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Close stale issues"

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 0 * * *"

jobs:
  default:
    timeout-minutes: 1

    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/stale@v8"
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          stale-issue-message: |
            This issue has been automatically marked as stale because it has been open for 21 days with no activity. It will be closed in 7 days if no further activity (Remove label or comment) occurs.
            If we missed this issue please reply to keep it active.
            Thanks for being a part of this project. 🙏
          stale-issue-label: "Stale"
          remove-stale-when-updated: true
          exempt-issue-labels: "Added,Enhancement,Changed,Deprecated,Fixed,Removed,Security,Status:
            Help wanted,Status: Needs Work,Status: Waiting for feedback,Type:
            Unconfirmed,Type: Bug"
          days-before-stale: 21
          days-before-close: 7

  invalid:
    timeout-minutes: 1

    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/stale@v8"
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          stale-issue-message: |
            This issue has been automatically marked as stale because it has been labeled as invalid.
            Thanks for being a part of this project. 🙏
          stale-issue-label: "Stale"
          only-labels: "Type: Unconfirmed"
          days-before-stale: 1
          days-before-close: 2

  duplicate:
    timeout-minutes: 1
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/stale@v8"
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          stale-issue-message: |
            This issue has been automatically marked as stale because it has been labeled as duplicate.
            Thanks for being a part of this project. 🙏
          stale-issue-label: "Stale"
          only-labels: "Duplicate"
          days-before-stale: 1
          days-before-close: 2

  wontfix:
    timeout-minutes: 1

    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/stale@v8"
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          stale-issue-message: |
            This issue has been automatically marked as stale because it has been labeled as wontfix.
            Thanks for being a part of this project. 🙏
          stale-issue-label: "Stale"
          only-labels: "Type: Wontfix"
          days-before-stale: 1
          days-before-close: 2
